"""empty message

Revision ID: 0587edfae7ec
Revises: 27a890e7b1af
Create Date: 2022-12-08 19:53:55.860762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0587edfae7ec'
down_revision = '27a890e7b1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gas_stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gas_stations_name'), ['name'], unique=False)

    op.create_table('fuels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gas_station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gas_station_id'], ['gas_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuels')
    with op.batch_alter_table('gas_stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gas_stations_name'))

    op.drop_table('gas_stations')
    # ### end Alembic commands ###
