"""add distance column

Revision ID: 9f02c46c1875
Revises: bc981a2767a5
Create Date: 2022-12-10 18:11:52.580041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f02c46c1875'
down_revision = 'bc981a2767a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gas_stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gas_stations', schema=None) as batch_op:
        batch_op.drop_column('distance')

    # ### end Alembic commands ###
