"""empty message

Revision ID: dcfc6b80f989
Revises: 66fb4189abdd
Create Date: 2023-01-05 22:01:52.225516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfc6b80f989'
down_revision = '66fb4189abdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gas_stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gas_stations', schema=None) as batch_op:
        batch_op.drop_column('average_rate')

    # ### end Alembic commands ###
